Repository cancervariants/fusion-curation, pull requests merged in 2024-08, with the labels that each got.

#297 cicd: pin exact ruff version
  .pre-commit-config.yaml
  server/pyproject.toml
Labels: priority:low

#299 refactor: address config deprecation
  server/src/curfu/schemas.py
Labels: priority:low

#298 feat: use latest fastapi event management api
  server/src/curfu/main.py
Labels: priority:low

#300 feat: update deprecated pytest async features
  server/tests/conftest.py
Labels: priority:low

#301 docs: remove docstring types and clean up formatting
  server/src/curfu/devtools/__init__.py
  server/src/curfu/devtools/build_interpro.py
  server/src/curfu/gene_services.py
  server/src/curfu/routers/__init__.py
  server/src/curfu/routers/complete.py
  server/src/curfu/routers/demo.py
  server/src/curfu/routers/lookup.py
  server/src/curfu/routers/utilities.py
  server/src/curfu/sequence_services.py
Labels: priority:low

#309 fix: handle unnecessary checks for build files
  README.md
  server/src/curfu/main.py
Labels: priority:medium

#312 cicd(fix): fix curfu path
  .ebextensions/01_build.config
Labels: bug, priority:high, ci/cd

#308 refactor: remove unused seqrepo configuration
  README.md
  server/src/curfu/__init__.py
  server/src/curfu/devtools/build_gene_suggest.py
Labels: priority:low

#314 feat!: update tx segment element with updated cool-seq-tool structure changes
  client/src/components/Pages/Structure/Input/TxSegmentElementInput/TxSegmentElementInput.tsx
  client/src/components/Pages/Summary/Main/Summary.tsx
  client/src/components/Utilities/GetCoordinates/GetCoordinates.tsx
  client/src/components/main/shared/ChromosomeField/ChromosomeField.tsx
  client/src/services/ResponseModels.ts
  client/src/services/main.tsx
  requirements.txt
  server/pyproject.toml
  server/src/curfu/routers/constructors.py
  server/src/curfu/routers/demo.py
  server/src/curfu/routers/utilities.py
  server/src/curfu/schemas.py
  server/tests/conftest.py
  server/tests/integration/test_constructors.py
  server/tests/integration/test_utilities.py
  server/tests/integration/test_validate.py
Labels: priority:high, build
