Repository cancervariants/fusion-curation, pull requests merged in 2024-09, with the labels that each got.

#273 feat: add transcript lookup for genes
  client/src/components/Pages/Structure/Builder/Builder.scss
  client/src/components/Pages/Structure/Input/StaticElement/StaticElement.tsx
  client/src/components/Pages/Structure/Input/StructuralElementInputProps.tsx
  client/src/components/Pages/Structure/Input/TxSegmentElementInput/TxSegmentElementInput.tsx
  client/src/components/Utilities/GetCoordinates/GetCoordinates.tsx
  client/src/components/Utilities/GetSequence/GetSequence.tsx
  client/src/components/Utilities/GetTranscripts/GetTranscripts.tsx
  client/src/components/main/shared/ChromosomeField/ChromosomeField.tsx
  client/src/components/main/shared/GeneAutocomplete/GeneAutocomplete.tsx
  client/src/components/main/shared/LoadingMessage/LoadingMessage.tsx
  client/src/components/main/shared/TabPaper/TabPaper.tsx
  client/src/components/main/shared/TranscriptField/TranscriptField.tsx
  client/src/services/ResponseModels.ts
  client/src/services/main.tsx
  server/pyproject.toml
  server/src/curfu/routers/constructors.py
  server/src/curfu/routers/demo.py
  server/src/curfu/routers/lookup.py
  server/src/curfu/schemas.py
  server/tests/integration/test_constructors.py
  server/tests/integration/test_lookup.py
Labels: priority:medium

#330 ci: add action for closing issue when merged into staging branch
  .github/workflows/close_issue.yml
Labels: priority:low, ci/cd

#331 fix: concurrency issue when elements were loading
  client/src/components/Pages/Structure/Builder/Builder.tsx
  client/src/components/Pages/Structure/Input/GeneElementInput/GeneElementInput.tsx
  client/src/components/Pages/Structure/Input/LinkerElementInput/LinkerElementInput.tsx
  client/src/components/Pages/Structure/Input/StructuralElementInputProps.tsx
  client/src/components/Pages/Structure/Input/TemplatedSequenceElementInput/TemplatedSequenceElementInput.tsx
  client/src/components/Pages/Structure/Input/TxSegmentElementInput/TxSegmentElementInput.tsx
Labels: bug, help wanted, priority:high

#332 feat: update tooltip for coordinate type, since we expect inter-resid…
  client/src/components/Pages/Structure/Input/TemplatedSequenceElementInput/TemplatedSequenceElementInput.tsx
  client/src/components/Pages/Structure/Input/TxSegmentElementInput/TxSegmentElementInput.tsx
Labels: priority:low

#334 fix: get coordinates not working for transcript
  client/src/components/Utilities/GetCoordinates/GetCoordinates.tsx
Labels: bug, priority:medium

#335 feat: add better error messaging
  client/src/components/Pages/Structure/Input/GeneElementInput/GeneElementInput.tsx
  client/src/components/Pages/Structure/Input/LinkerElementInput/LinkerElementInput.tsx
  client/src/components/Pages/Structure/Input/RegulatoryElementInput/RegulatoryElementInput.tsx
  client/src/components/Pages/Structure/Input/StructuralElementInputAccordion.tsx
  client/src/components/Pages/Structure/Input/TemplatedSequenceElementInput/TemplatedSequenceElementInput.tsx
  client/src/components/Pages/Structure/Input/TxSegmentElementInput/TxSegmentElementInput.tsx
  client/src/components/Pages/Summary/Invalid/Invalid.tsx
  client/src/components/Pages/Summary/Main/Summary.tsx
  requirements.txt
  server/pyproject.toml
  server/src/curfu/routers/validate.py
Labels: enhancement, priority:medium

#336 fix: unable to construct tx segment when genomic coordinate between e…
  client/src/components/Pages/Structure/Input/TxSegmentElementInput/TxSegmentElementInput.tsx
  requirements.txt
  server/pyproject.toml
  server/src/curfu/routers/constructors.py
  server/src/curfu/routers/utilities.py
  server/tests/integration/test_utilities.py
Labels: priority:medium
