Repository cancervariants/fusion-curation, pull requests merged in 2024-07, with the labels that each got.

#286 cicd: update precommit
  .pre-commit-config.yaml
  server/setup.cfg
Labels: priority:low

#285 build!: define in pyproject.toml
  .gitignore
  LICENSE
  Procfile
  server/curfu/version.py
  server/pyproject.toml
  server/setup.cfg
  server/setup.py
  server/src/curfu/__init__.py
  server/src/curfu/cli.py
  server/src/curfu/devtools/__init__.py
  server/src/curfu/devtools/build_client_types.py
  server/src/curfu/devtools/build_gene_suggest.py
  server/src/curfu/devtools/build_interpro.py
  server/src/curfu/domain_services.py
  server/src/curfu/gene_services.py
  server/src/curfu/main.py
  server/src/curfu/routers/__init__.py
  server/src/curfu/routers/complete.py
  server/src/curfu/routers/constructors.py
  server/src/curfu/routers/demo.py
  server/src/curfu/routers/lookup.py
  server/src/curfu/routers/meta.py
  server/src/curfu/routers/nomenclature.py
  server/src/curfu/routers/utilities.py
  server/src/curfu/routers/validate.py
  server/src/curfu/schemas.py
  server/src/curfu/sequence_services.py
  server/src/curfu/utils.py
Labels: priority:medium

#287 cicd: fix stalebot
  .github/workflows/stale.yaml
Labels: priority:low

#288 Staging
  .flake8
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/workflows/backend_checks.yml
  .github/workflows/pr-priority-label.yaml
  .github/workflows/stale.yaml
  .gitignore
  .pre-commit-config.yaml
  LICENSE
  Procfile
  client/src/components/Pages/CausativeEvent/CausativeEvent.tsx
  client/src/components/Pages/Structure/Input/GeneElementInput/GeneElementInput.tsx
  client/src/components/Pages/Structure/Input/StaticElement/StaticElement.tsx
  client/src/components/Pages/Structure/Input/StructuralElementInputAccordion.tsx
  client/src/components/Pages/Structure/Input/StructuralElementInputProps.tsx
  client/src/components/Pages/Structure/Input/TemplatedSequenceElementInput/TemplatedSequenceElementInput.tsx
  client/src/components/Pages/Structure/Input/TxSegmentElementInput/TxSegmentElementInput.tsx
  client/src/components/Pages/Summary/Invalid/Invalid.tsx
  client/src/components/Pages/Summary/Readable/Readable.tsx
  client/src/components/Utilities/GetCoordinates/GetCoordinates.tsx
  client/src/components/main/App/App.tsx
  client/src/components/main/App/AppMenu.tsx
  client/src/components/main/shared/ChromosomeField/ChromosomeField.tsx
  client/src/components/main/shared/GeneAutocomplete/GeneAutocomplete.tsx
  client/src/components/main/shared/HelpTooltip/HelpTooltip.tsx
  client/src/global/contexts/SettingsContext.tsx
  requirements.txt
  server/.flake8
  server/curfu/version.py
  server/pyproject.toml
  server/setup.cfg
  server/setup.py
  server/src/curfu/__init__.py
  server/src/curfu/cli.py
  server/src/curfu/devtools/__init__.py
  server/src/curfu/devtools/build_client_types.py
  server/src/curfu/devtools/build_gene_suggest.py
  server/src/curfu/devtools/build_interpro.py
  server/src/curfu/domain_services.py
  server/src/curfu/gene_services.py
  server/src/curfu/main.py
  server/src/curfu/routers/__init__.py
  server/src/curfu/routers/complete.py
  server/src/curfu/routers/constructors.py
  server/src/curfu/routers/demo.py
  server/src/curfu/routers/lookup.py
  server/src/curfu/routers/meta.py
  server/src/curfu/routers/nomenclature.py
  server/src/curfu/routers/utilities.py
  server/src/curfu/routers/validate.py
  server/src/curfu/schemas.py
  server/src/curfu/sequence_services.py
  server/src/curfu/utils.py
  server/tests/conftest.py
  server/tests/integration/test_complete.py
  server/tests/integration/test_main.py
  server/tests/integration/test_nomenclature.py
  server/tests/integration/test_utilities.py
  server/tests/integration/test_validate.py
Labels: priority:low

#289 build: fix setuptools-scm build
  server/pyproject.toml
Labels: priority:high

#283 style: update ruff and drop black
  .github/workflows/backend_checks.yml
  .pre-commit-config.yaml
  server/pyproject.toml
  server/src/curfu/__init__.py
  server/src/curfu/cli.py
  server/src/curfu/devtools/__init__.py
  server/src/curfu/devtools/build_client_types.py
  server/src/curfu/devtools/build_gene_suggest.py
  server/src/curfu/devtools/build_interpro.py
  server/src/curfu/domain_services.py
  server/src/curfu/gene_services.py
  server/src/curfu/main.py
  server/src/curfu/routers/complete.py
  server/src/curfu/routers/constructors.py
  server/src/curfu/routers/demo.py
  server/src/curfu/routers/lookup.py
  server/src/curfu/routers/meta.py
  server/src/curfu/routers/nomenclature.py
  server/src/curfu/routers/utilities.py
  server/src/curfu/routers/validate.py
  server/src/curfu/schemas.py
  server/src/curfu/sequence_services.py
  server/src/curfu/utils.py
  server/tests/conftest.py
  server/tests/integration/test_complete.py
  server/tests/integration/test_constructors.py
  server/tests/integration/test_demos.py
  server/tests/integration/test_lookup.py
  server/tests/integration/test_main.py
  server/tests/integration/test_nomenclature.py
  server/tests/integration/test_utilities.py
  server/tests/integration/test_validate.py
Labels: priority:low

#291 cicd: allow missing credentials
  .pre-commit-config.yaml
Labels: priority:low

#292 chore: update ebextensions for downloading latest seqrepo instance
  .ebextensions/02_data_downloads.config
Labels: priority:medium, chore
